version: '3' 
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example 
  weblate:
    image: weblate/weblate 
    ports:
      - 80:8080
    environment:
      WEBLATE_ALLOWED_HOSTS: weblate.example.com,localhost
      WEBLATE_ADMIN_PASSWORD: password for the admin user
      WEBLATE_ADMIN_EMAIL: weblate.admin@example.com