version: '3' 
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example 
  weblate:
    image: weblate/weblate 
    ports:
      - 80:8080
    environment:
      