version: '3' 
services:
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - /home/centos/data:/var/lib/postgresql
  redis:
    container_name: cache
    image: redis 
    ports: 
      - 6379:6379
  weblate:
    image: weblate/weblate 
    restart: always
    ports:
      - 80:8080
    environment:
      WEBLATE_ALLOWED_HOSTS: localhost,34.68.22.78
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_ADMIN_NAME: Admin
      WEBLATE_ADMIN_EMAIL: admin@local.com
      WEBLATE_SERVER_EMAIL: weblate@local.com
      WEBLATE_DEFAULT_FROM_EMAIL: weblate@local.com
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432