version: '3' 
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example 
  weblate:
    image: weblate/weblate 
    ports:
      - 80:8080
    environment:
      WEBLATE_ALLOWED_HOSTS: localhost
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_ADMIN_EMAIL: admin@local.com
      POSTGRES_PASSWORD: example