version: '3' 
services:
  postgresql:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example 
  weblate:
    image: weblate/weblate 
    ports:
      - 80:8080
    environment:
      WEBLATE_ALLOWED_HOSTS: localhost
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_ADMIN_NAME: Admin
      WEBLATE_ADMIN_EMAIL: admin@local.com
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: localhost 
      POSTGRES_USER: postgres
      POSTGRES_PORT: 