version: '3' 
services:
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example 
  redis:
    container_name: cache
    image: redis 
    ports: 
      - 6379:6379
  weblate:
    image: weblate/weblate 
    ports:
      - 80:8080
    environment:
      WEBLATE_ALLOWED_HOSTS: localhost
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_ADMIN_NAME: Admin
      WEBLATE_ADMIN_EMAIL: admin@local.com
      WEBLATE_SERVER_EMAIL: weblate@local.com
      WEBLATE_DEFAULT_FROM_EMAIL: weblate@local.com
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: localhost 
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432